services:
  buecherhallen-scraper:
    build:
      context: https://github.com/dominik-bauer/buecherhallen-scraper.git#main
      dockerfile: Dockerfile
    container_name: buecherhallen-scraper
    restart: unless-stopped
    ports:
      - 8321:8080 # Host-Port : Container-Port
networks: {}
