services:
  buecherhallen-scraper:
    build:
      context: https://github.com/dominik-bauer/buecherhallen-scraper.git#main
      dockerfile: Dockerfile
    container_name: buecherhallen-scraper
    restart: unless-stopped
    ports:
      - 8282:8080 # Host-Port : Container-Port
    environment:
      APP_VAR1: null
      APP_VAR2: null
      APP_VAR3: null
networks: {}